// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKEuIeaM1oQRLmpOsDKu0a1Fzk61ZkxHI',
    appId: '1:1020728733372:web:a605fce04e3fd26c1faab9',
    messagingSenderId: '1020728733372',
    projectId: 'crm-p-3f09b',
    authDomain: 'crm-p-3f09b.firebaseapp.com',
    storageBucket: 'crm-p-3f09b.firebasestorage.app',
    measurementId: 'G-MTQWYE70Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYurg1puLjjP0nlmZteyBAoWFTpL_QwAM',
    appId: '1:1020728733372:android:ee0319c4075e89041faab9',
    messagingSenderId: '1020728733372',
    projectId: 'crm-p-3f09b',
    storageBucket: 'crm-p-3f09b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4iSskUohLp6LBMZjKHOP4xttgqV0hbNU',
    appId: '1:1020728733372:ios:e3aac8d6a9eb45e51faab9',
    messagingSenderId: '1020728733372',
    projectId: 'crm-p-3f09b',
    storageBucket: 'crm-p-3f09b.firebasestorage.app',
    iosBundleId: 'com.example.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4iSskUohLp6LBMZjKHOP4xttgqV0hbNU',
    appId: '1:1020728733372:ios:e3aac8d6a9eb45e51faab9',
    messagingSenderId: '1020728733372',
    projectId: 'crm-p-3f09b',
    storageBucket: 'crm-p-3f09b.firebasestorage.app',
    iosBundleId: 'com.example.crm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKEuIeaM1oQRLmpOsDKu0a1Fzk61ZkxHI',
    appId: '1:1020728733372:web:cde038b3fc41f7ba1faab9',
    messagingSenderId: '1020728733372',
    projectId: 'crm-p-3f09b',
    authDomain: 'crm-p-3f09b.firebaseapp.com',
    storageBucket: 'crm-p-3f09b.firebasestorage.app',
    measurementId: 'G-N2MVWQZ07L',
  );
}
